# Generated by Django 3.2.4 on 2021-08-31 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField(blank=True, default='')),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'snippets',
                'ordering': ['-created'],
            },
        ),
    ]
